[package]
name = "nwa"
version = "0.1.0"
authors = ["Nils Hasenbanck <nils@hasenbanck.de>"]
edition = "2018"

[lib]
name = "nwa"
path = "src/lib.rs"

[[bin]]
name = "nwatowav"
path = "src/main.rs"

[dependencies]
byteorder = "1"
failure = "0.1.5"
structopt = "0.2"
rayon = "1.1"
